### PR TITLE
Fix virtual attributes and IN clauses

### PR DESCRIPTION
**Pull request by kbrock**
6.1 introduced `HomogeneousIn`, an optimization for the `In` clause.
This introduced changes to `Attribute` that required our attention.

An attribute now needs to have a `name`, and be able to type cast parameters for the
datatype.

This change gives the virtual attribute more information for type casting.

Put in a PR for rails to hopefully remove our requirement to monkey patch
that operator. https://github.com/rails/rails/pull/45642

### CODE REVIEW

**Comment by Fryguy** [comment]
> Put in a PR for rails to hopefully remove our requirement to monkey patch
that operator.

Can you link the Rails PR?

**Comment by jrafanie** [comment]
To be clear, does this PR work with rails 6.0?  I'm good with this change but am curious how we'll version this if it no longer works with 6.0.

**Comment by kbrock** [comment]
@jrafanie Our versions are for a single version of rails.

This change is only for HEAD / virtual attributes 6.1.x / ActiveRecord 6.1.x
If we want a change for 6.0, then we can backport to an older version.

So yes, this will not break previous versions of rails because they will not use this version of virtual attributes.

**Comment by jrafanie** [comment]
> @jrafanie Our versions are for a single version of rails.
> 
> This change is only for HEAD / virtual attributes 6.1.x / ActiveRecord 6.1.x If we want a change for 6.0, then we can backport to an older version.

Right.  Thanks.

**Review by jrafanie — APPROVED** [review]

**Comment by jrafanie** [comment]
We'll need a tagged release for this change.

**Pull request merged**
