### PR TITLE
[WIP] AR::AttributeSet changed to ActiveModel base class

### PR DESCRIPTION
**Pull request by juliancheal**
This change is in Rails 5.2.x

### CODE REVIEW

**Comment by kbrock** [comment]
other branch changed again - go ahead and steal from there for some other ideas

**Comment by juliancheal** [comment]
@kbrock I'm not sure what I need to pull in, I assume your pr is way better by now anyway?

**Comment by kbrock** [comment]
@juliancheal mine is better NOW.
But I assume you're going to improve mine and repost here?

**Comment by kbrock** [comment]
ok, closing this.

please open again to fix up the stuff that just got merged (if it needs any fixing that is)

**Pull request closed without merging**
