### PR TITLE
remove rails 61 version check

### PR DESCRIPTION
**Pull request by kbrock**
We used to support multiple rails versions in the same branch.
Now we are using different branches per rails version.
So there is no need to have a version check

### CODE REVIEW

**Comment by jrafanie** [comment]
LGTM, let's revisit this once 6.1.1 is released and we have rails 6.1 working.

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
manageiq 6.1 PR is merged.

**Review by jrafanie — APPROVED** [review]
LGTM, is this ready to merge @kbrock ?

**Comment by kbrock** [comment]
@jrafanie yea, ready to go

**Pull request merged**
